var sliderImages = [
    "./assets/banner1.jpg",
    "./assets/news2.jpg",
    "./assets/banner1.jpg",
    "./assets/news2.jpg",
    "./assets/banner1.jpg",
    "./assets/news2.jpg"
];
var artistList = [
{ "name" :"Franz Ackermann","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Etel Adnan","imageSrc" : "./assets/banner1.jpg"},
{ "name" :"Darren Almond","imageSrc" : "./assets/news1.jpg"},
{ "name" :"Ellen Altfest","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Michael Armitage","imageSrc" : "./assets/news1.jpg"},
{ "name" :"Miroslaw Balka","imageSrc" : "./assets/news2.jpg"},
{ "name" :"Georg Baselitz","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Larry Bell","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Jake & Dinos Chapman","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Chuck Close","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Gregory Crewdson","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Tracey Emin","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Katharina Fritsch","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Theaster Gates","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Gilbert & George","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Antony Gormley","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Andreas Gursky","imageSrc" : "./assets/artist.jpg"},
{ "name" :"David Hammons","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Mona Hatoum","imageSrc" : "./assets/artist.jpg"},
{ "name" :"He Xiangyu","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Damien Hirst","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Robert Irwin","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Runa Islam","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Sergej Jensen","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Anselm Kiefer","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Rachel Kneebone","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Imi Knoebel","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Elad Lassry","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Liza Lou","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Jac Leirner","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Liu Wei","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Christian Marclay","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Josiah McElheny","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Julie Mehretu","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Beatriz Milhazes","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Harland Miller","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Sarah Morris","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Gabriel Orozco","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Damián Ortega","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Virginia Overton","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Eddie Peake","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Magnus Plessen","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Jessica Rankin","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Christian Rosa","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Doris Salcedo","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Raqib Shaw","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Haim Steinbach","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Sam Taylor-Johnson","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Fred Tomaselli","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Jeff Wall","imageSrc" : "./assets/artist.jpg"},
{ "name" :"Cerith Wyn Evans","imageSrc" : "./assets/artist.jpg"}]